### ISSUE TITLE
riksdagen scraper

### ISSUE THREAD

**Issue by ghost** [LameLemon/scrapers#4]
riksdagen erroring out with 
"Bad status code for Hxxxxx" see pictures
![unknown](https://user-images.githubusercontent.com/103267526/176392200-536e810b-7d1c-473b-afda-86575743ed31.png)

**Comment by PeskyPotato** [comment]
Hi, pushed a commit to the Riksdagen scraper a while ago to update the API (aa6e53d25ec47f9e82c35bc71fd06de0b6e6f75f). Still getting the same errors?

**Comment by PeskyPotato** [comment]
Works!
